### ISSUE TITLE
Weidmuller on top interferes with sample case

### ISSUE THREAD

**Issue by ngreen-gt** [PlayingWithFusion/SnakeEyesDocs#1]
The sample case only fits if you solder the  Weidmuller connector to the bottom of the board, otherwise the case hits the connector.    In the video, it says either side is okay (06:30).  A note in sampleCase.md on this would be helpful.

**Comment by gerth2** [comment]
#4 should add comments about it.

I was poking around at how to accommodate it in the case (the onshape model has an older board that didn't model it). Adding a cutout might be feasilbe?

**Comment by gerth2** [comment]
Two new case designs added to reduce these issues.
