### ISSUE TITLE
stl download

### ISSUE THREAD

**Issue by SuntheMoonandStars** [PlayingWithFusion/SnakeEyesDocs#2]
Hi I'm having a problem downloading your stl files. Chrome just opens a window with the text. I would like to put the files into fusion 360 and modify the face of the top to add our teams logo and number. I assume this needs to go direct into a slicer.

solid Onshape
  facet normal 0 0.999763 -0.021773
    outer loop
      vertex -99.7804 17 9.5
      vertex -103 17 9.5
      vertex -99.7804 17.001 9.54362
    endloop

lots more lines

**Comment by gerth2** [comment]
#4 should address this, with all files getting zipped for download in the release area. - I'll close this out for now, but feel free to re-open if you run into issues.
