### ISSUE TITLE
Case source files?

### ISSUE THREAD

**Issue by allengregoryiv** [PlayingWithFusion/SnakeEyesDocs#5]
Is it possible to get a STEP or source CAD files for the snake eyes case? Modifying the STL files is not the easiest/cleanest way to go.

**Comment by fusionstein** [comment]
Hi Allen, the full CAD is available in Onshape here: https://cad.onshape.com/documents/f103c7ef3fd26794c458b982/w/31e132f18a5a8b15dab352ca/e/fb93b9d1fb39f2f70ae6d80d

Let me know if you have any questions, and have a great weekend! If all goes well, we'll post a video or two showing our start to the vision solution. 

-Justin
