### ISSUE TITLE
Included bolts not long enough for latest version of the case

### ISSUE THREAD

**Issue by viggy96** [PlayingWithFusion/SnakeEyesDocs#7]
I recently purchased a SnakeEyes hat, and I printed the latest version of the case, however, I found that the longer 25mm bolts aren't long enough to reach to the top piece and thread onto the nuts. I had to go back to the 2022 version. 

I spent ages trying to figure out what I was doing wrong when assembling the unit.

**Comment by gerth2** [comment]
new case designs have been added to address the issues.
